ALTER TABLE pages ADD COLUMN IF NOT EXISTS og_image TEXT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS language TEXT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS favicon_url TEXT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS read_time_minutes INT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS site_name TEXT;
